-- Flight data expansion notes and safe SQL scaffolds
-- These statements are intentionally documented as notes first. Review RLS,
-- backfill behavior, and source licensing before applying to production.

-- 1) Candidate columns for richer flight snapshots.
-- alter table public.flights add column if not exists departure_time timestamptz;
-- alter table public.flights add column if not exists arrival_time timestamptz;
-- alter table public.flights add column if not exists cabin_open_seats integer;
-- alter table public.flights add column if not exists standby_count integer;
-- alter table public.flights add column if not exists source_name text;
-- alter table public.flights add column if not exists source_checked_at timestamptz;

-- 2) Route watchlist persistence scaffold.
-- create table if not exists public.saved_routes (
--   id bigint generated by default as identity primary key,
--   user_id uuid references auth.users(id) on delete cascade,
--   origin text not null,
--   destination text not null,
--   alert_rule text not null default 'score_above_75',
--   cadence text not null default 'daily',
--   created_at timestamptz not null default now()
-- );

-- 3) Data-source audit trail scaffold.
-- create table if not exists public.flight_data_imports (
--   id bigint generated by default as identity primary key,
--   source_name text not null,
--   status text not null,
--   rows_seen integer not null default 0,
--   rows_upserted integer not null default 0,
--   notes text,
--   created_at timestamptz not null default now()
-- );

-- 4) Helpful indexes once columns/tables are live.
-- create index if not exists flights_route_idx on public.flights (origin, destination);
-- create index if not exists flights_number_idx on public.flights (flight_number);
-- create index if not exists saved_routes_user_route_idx on public.saved_routes (user_id, origin, destination);
